server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://vManav123:root@cluster1.dxvl7.mongodb.net/Railway-Reservation-System?retryWrites=true&w=majority
  application:
    name: RAILWAY-RESERVATION-SERVICE

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
