server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://vManav123:root@cluster1.dxvl7.mongodb.net/Railway-Reservation-System?retryWrites=true&w=majority
  application:
    name: User-Management-Service
  cloud:
    config:
      server:
        git:
          uri:
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}